source: [
name = "documentmaker"
url = "https://awesomewithrex.github.io/Python-Document-Maker/"
twitter = "none"

dev-packages: [

]

packages: [

]

requires: [
python_version = "3.8"
]

other: [
later_ver_usable = "true"
]
]
